apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: gitops-test
spec:
  subscriptions:
    repos:
      images:
        - repoURL: docker.io/niiku/gitops-nginx-demo
#          semverConstraint: ^1.24.0
