app:
  replicaCount: 2
  image:
    repository: docker.io/niiku/gitops-nginx-demo
    tag: v0.1.0
  network:
    http:
      servicePort: 8080
      ingress:
        host: gitops-int.apps.baloise.dev
  readinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 5
    timeoutSeconds: 1
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 1
      memory: 32Mi
